#!/usr/bin/python
import argparse
import os
import re

RE_CONNECT = re.compile(r'\\connect (")?(.*)(?(1)\1)')


def main(postgres, directory):
    with open(postgres) as in_file:
        active_database = None
        for line in in_file.readlines():
            match = RE_CONNECT.match(line)
            if match:  # the line starts with \connect
                if active_database:
                    active_database.close()

                path = os.path.join(directory, match.group(2))
                active_database = open(path, 'w')

            if active_database:
                active_database.write(line)

        if active_database:
            active_database.close()


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("PostgresDump", help="Path to the Postgres dump file")
    parser.add_argument("Directory", help="Directory to save the files")
    args = parser.parse_args()

    exit(main(postgres=args.PostgresDump, directory=args.Directory))
